version: '3.1'
services:
  apache:
    image: httpd:latest
    container_name: webapache
    ports:
    - '8000:80'
    volumes:
    - ./apache/htdocs:/usr/local/apache2/htdocs
  webserver:
    image: nginx:alpine
    container_name: webserver
    volumes:
    - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/config/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/html:/usr/share/nginx/html
    restart: unless-stopped
    ports:
      - "800:80"
      - "4430:443"